language: rust
rust:
        - nightly
services:
        - postgresql
        - redis-server
before_script:
        - psql -c 'create database diesel;' -U postgres
        - psql -c 'create extension if not exists "uuid-ossp";' -U postgres diesel
        - echo "DATABASE_URL=postgres://postgres@localhost/diesel" > .env
        - cargo install diesel_cli --force --no-default-features --features=postgres
        - diesel migration run
        - echo "REDIS_URL=redis://localhost/" >> .env
script:
        - cargo build --verbose --all
        - cargo test --verbose --all
cache: cargo
